name: Deploy Static Resume

on:
  push:
    branches: [ main ]
    paths:
      - '02-static-cdn-serverless-form/site/**'
      - '.github/workflows/deploy-static.yml'
  workflow_dispatch: {}

concurrency:
  group: static-site-deploy
  cancel-in-progress: true

env:
  AWS_REGION: ap-southeast-1
  ROLE_ARN: arn:aws:iam::818719120332:role/GitHubDeployerRole
  S3_BUCKET: cv.whynotcloud.ltd
  CF_DISTRIBUTION_ID: EC6W5QTV3MYAG
  SITE_DIR: 02-static-cdn-serverless-form/site
  BUILD_DIR: ''   # 有打包产物就写 dist

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (assume role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Decide upload folder
        id: paths
        run: |
          set -euo pipefail
          if [ -n "${BUILD_DIR}" ] && [ -d "${SITE_DIR}/${BUILD_DIR}" ]; then
            echo "UPLOAD_DIR=${SITE_DIR}/${BUILD_DIR}" >> $GITHUB_OUTPUT
          else
            echo "UPLOAD_DIR=${SITE_DIR}" >> $GITHUB_OUTPUT
          fi

      - name: Sync assets (long cache)
        run: |
          set -euo pipefail
          aws s3 sync "${{ steps.paths.outputs.UPLOAD_DIR }}/" "s3://${{ env.S3_BUCKET }}/" \
            --delete --follow-symlinks \
            --exclude "*.html" \
            --cache-control "public,max-age=31536000,immutable" \
            --only-show-errors

      - name: Sync html (no cache)
        run: |
          set -euo pipefail
          aws s3 sync "${{ steps.paths.outputs.UPLOAD_DIR }}/" "s3://${{ env.S3_BUCKET }}/" \
            --delete --follow-symlinks \
            --exclude "*" --include "*.html" \
            --cache-control "no-cache" \
            --only-show-errors

      - name: Invalidate CloudFront (index only)
        if: env.CF_DISTRIBUTION_ID != ''
        run: |
          set -euo pipefail
          aws cloudfront create-invalidation \
            --distribution-id "${{ env.CF_DISTRIBUTION_ID }}" \
            --paths "/index.html"
